// Церковно-славянская азбука с названиями букв и ударениями
const churchSlavonicAlphabet = [
    { uppercase: "А", lowercase: "а", name: "а́зъ" },
    { uppercase: "Б", lowercase: "б", name: "бу́ки" },
    { uppercase: "В", lowercase: "в", name: "вѣ́ди" },
    { uppercase: "Г", lowercase: "г", name: "глаго́ль" },
    { uppercase: "Д", lowercase: "д", name: "добро́" },
    { uppercase: "Є", lowercase: "є", name: "є́сть" },
    { uppercase: "Ж", lowercase: "ж", name: "живѣ́тє" },
    { uppercase: "Ꙃ", lowercase: "ꙃ", name: "ѕѣло́" },
    { uppercase: "З", lowercase: "з", name: "земля́" },
    { uppercase: "И", lowercase: "и", name: "и́же" },
    { uppercase: "І", lowercase: "і", name: "и" },
    { uppercase: "К", lowercase: "к", name: "како́" },
    { uppercase: "Л", lowercase: "л", name: "лю́диє" },
    { uppercase: "М", lowercase: "м", name: "мыслѣ́тє" },
    { uppercase: "Н", lowercase: "н", name: "нашь" },
    { uppercase: "О", lowercase: "о", name: "о́нъ" },
    { uppercase: "П", lowercase: "п", name: "поко́й" },
    { uppercase: "Р", lowercase: "р", name: "рьци́" },
    { uppercase: "С", lowercase: "с", name: "сло́во" },
    { uppercase: "Т", lowercase: "т", name: "тве́рдо" },
    { uppercase: "Ѵ", lowercase: "ѵ", name: "у́къ" },
    { uppercase: "Ф", lowercase: "ф", name: "фе́ртъ" },
    { uppercase: "Х", lowercase: "х", name: "хѣ́ръ" },
    { uppercase: "Ѡ", lowercase: "ѡ", name: "о́тъ" },
    { uppercase: "Ц", lowercase: "ц", name: "ци" },
    { uppercase: "Ч", lowercase: "ч", name: "че́рвь" },
    { uppercase: "Ш", lowercase: "ш", name: "ша" },
    { uppercase: "Щ", lowercase: "щ", name: "шча" },
    { uppercase: "Ъ", lowercase: "ъ", name: "є́ръ" },
    { uppercase: "Ы", lowercase: "ы", name: "є́ры" },
    { uppercase: "Ь", lowercase: "ь", name: "є́рь" },
    { uppercase: "Ѣ", lowercase: "ѣ", name: "ять" },
    { uppercase: "Ю", lowercase: "ю", name: "ю" },
    { uppercase: "Ꙗ", lowercase: "ꙗ", name: "я́" },
    { uppercase: "Ѥ", lowercase: "ѥ", name: "є́" },
    { uppercase: "Ѧ", lowercase: "ѧ", name: "ю́съ ма́лъ" },
    { uppercase: "Ѩ", lowercase: "ѩ", name: "ю́съ" },
    { uppercase: "Ѫ", lowercase: "ѫ", name: "ю́съ вели́къ" },
    { uppercase: "Ѭ", lowercase: "ѭ", name: "ю́съ" },
    { uppercase: "Ѯ", lowercase: "ѯ", name: "кси́" },
    { uppercase: "Ѱ", lowercase: "ѱ", name: "пси́" },
    { uppercase: "Ѳ", lowercase: "ѳ", name: "ѳи́та" },
    { uppercase: "Ѵ", lowercase: "ѵ", name: "ижи́ца" }
];

// Экспорт для использования в других файлах
if (typeof module !== 'undefined' && module.exports) {
    module.exports = churchSlavonicAlphabet;
}